ALTER SESSION SET CURRENT_SCHEMA = app_owner;

CREATE EDITION ED_2;
ALTER SESSION SET EDITION = ED_2;

CREATE OR REPLACE EDITIONING VIEW staff_view AS
  SELECT title, firstname, surname  FROM staff;

GRANT USE ON EDITION ED_2 TO app_readonly;
